
data_document <- function(dd) {

  dd %>%
    set_labels(risk_horizon  = "time of risk prediction",
               overall  = "Overall",
               study  = "Study",
               lpa_nmol  = "Lp(a)",
               lpa_mgdl  = "Lp(a)",
               lpa_nmol_log  = "Log Lp(a)",
               lpa_mgdl_log  = "Log Lp(a)",
               status_ascvd  = "ASCVD event",
               time_ascvd  = "Time to ASCVD",
               status_cvd  = "CVD event",
               time_cvd  = "Time to CVD",
               status_chd  = "CHD event",
               time_chd  = "Time to CHD",
               cvd_risk_10yr  = "10-year CVD risk",
               cvd_risk_30yr  = "30-year CVD risk",
               chd_risk_10yr  = "10-year CHD risk",
               chd_risk_30yr  = "30-year CHD risk",
               ascvd_risk_10yr  = "10-year ASCVD risk",
               ascvd_risk_30yr  = "30-year ASCVD risk",
               age  = "Age",
               sex  = "Sex",
               race  = "Race/ethnicity",
               bmi  = "Body mass index",
               smoke_current  = "Current smoking",
               etoh_current  = "Alcohol use",
               hx_stroke  = "History of stroke",
               hx_chd  = "History of CHD",
               hx_hf  = "History of heart failure",
               waist_hip_ratio  = "Waist to hip ratio",
               diabetes  = "Type II diabetes",
               htn  = "Hypertension",
               chol_total  = "Total cholesterol",
               chol_hdl  = "HDL-cholesterol",
               chol_ldl  = "LDL-cholesterol",
               med_chol  = "Cholesterol medication use",
               egfr_2021  = "Estimated GFR",
               egfr_lt60 = "Estimated GFR < 60 ml/min/1.73m2",
               sbp  = "Systolic blood pressure",
               dbp  = "Diastolic blood pressure",
               uacr  = "Urine albumin-to-creatinine ratio",
               med_statin  = "Statin use",
               med_htn  = "Antihypertensive medication use",
               trigs  = "Triglycerides") %>%
    set_category_labels(overall = c(overall = "Overall"),
                        study = c(aric = "ARIC",
                                  mesa = "MESA",
                                  cardia_train = "CARDIA (training)",
                                  cardia_test = "CARDIA (testing)"),
                        sex = c(male = "Men",
                                female = "Women"),
                        race = c(white = "White",
                                 black = "Black",
                                 hispanic = "Hispanic",
                                 east_asian = "East Asian")) %>%
    set_units(lpa_nmol  = "nmol/L",
              lpa_mgdl  = "mg/dL",
              lpa_nmol_log  = "log nmol/L",
              lpa_mgdl_log  = "log mg/dL",
              time_ascvd  = "years",
              time_cvd  = "years",
              time_chd  = "years",
              cvd_risk_10yr  = "%",
              cvd_risk_30yr  = "%",
              chd_risk_10yr  = "%",
              chd_risk_30yr  = "%",
              ascvd_risk_10yr  = "%",
              ascvd_risk_30yr  = "%",
              age  = "years",
              bmi  = "kg/m2",
              chol_total  = "mg/dL",
              chol_hdl  = "mg/dL",
              chol_ldl  = "mg/dL",
              egfr_2021  = "ml/min/1.73m2",
              sbp  = "mm Hg",
              dbp  = "mm Hg",
              trigs  = "mg/dL") %>%
    set_divby_modeling(lpa_nmol = 25,
                       lpa_mgdl = 25,
                       age = 10,
                       bmi = 5,
                       chol_total = 20,
                       chol_hdl = 10,
                       sbp = 15)

}
